# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.6.1/charts/library/common/values.schema.json
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  securityContext:
    # -- Run as `nobody` user
    runAsUser: 65534
    # -- Run as `nobody` group
    runAsGroup: 65534
    # -- Volume binds will be granted to `nobody` group
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
    # fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true
  priorityClassName: normal-priority

controllers:
  main:
    revisionHistoryLimit: 0
    annotations: 
      reloader.stakater.com/auto: "true"
    defaultContainerOptions:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]

extraObjects: []

persistence:
  tmp:
    enabled: true
    type: emptyDir
    sizeLimit: 2Gi
    globalMounts:
      - path : /tmp

code:
  enabled: false
  ingressHost: ""
  dataPath: ""