---
{{- include "bjw-s.common.loader.init" . }}

{{- define "general.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ if $.Values.code.enabled }}
controllers:
  main:
    containers:
      code:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.92.2
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/data/.vscode"
          - --extensions-dir
          - "/data/.vscode"
          - --port
          - "8081"
          - "/data"
service:
  code:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8081
ingress:
  code:
    enabled: true
    className: traefik-internal
    annotations:
      "traefik.ingress.kubernetes.io/router.middlewares": traefik-localonly@kubernetescrd
    hosts:
      - host: {{ $.Values.code.ingressHost }}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: code
{{ end }}
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "general.hardcodedValues" . | fromYaml) -}}
{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}