---
{{- include "bjw-s.common.loader.init" . }}

{{- define "general.hardcodedValues" -}}
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ if $.Values.code.enabled }}
controllers:
  main:
    containers:
      code:
        enabled: true
        image:
          repository: gitpod/openvscode-server
          tag: latest
        args:
          - --auth
          - "none"
          - --disable-getting-started-override
          - --user-data-dir
          - "{{ $.Values.code.dataPath }}/.vscode"
          - --extensions-dir
          - "{{ $.Values.code.dataPath }}/.vscode"
          - --config
          - "{{ $.Values.code.dataPath }}/.vscode"
          - --port
          - "8081"
          - "{{ $.Values.code.dataPath }}"
        env:
          DOCKER_USER: {{ coalesce $.Values.controllers.main.containers.main.securityContext.runAsUser $.Values.defaultPodOptions.securityContext.runAsUser}}

service:
  code:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8081
ingress:
  code:
    enabled: true
    className: traefik-internal
    annotations:
      "traefik.ingress.kubernetes.io/router.middlewares": traefik-localonly@kubernetescrd
    hosts:
      - host: {{ $.Values.code.ingressHost }}
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: code

persistence:
  nonexistent:
    enabled: true
    type: emptyDir
    sizeLimit: 2Gi
    advancedMounts:
      main:
        code:
          - path: /nonexistent
{{ end }}
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "general.hardcodedValues" . | fromYaml) -}}
{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}